# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nest-apu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 130

      - name: npm install, build, and test
        run: |
          npm install -g @nestjs/cli
          npm install
          npx prisma generate
          npm run build
#          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C4D7A04C8336400E9B9A6C919B98D540 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B99544BFF74048C985C1BEC7695C7E18 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A48B3E26FD342DE9839D18DD582E80B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nest-apu'
          slot-name: 'Production'
          package: .
